### ISSUE TITLE
Trajectory succeeds while robot is still moving

### ISSUE THREAD

**Issue by Tonkel** [personalrobotics/rewd_controllers#21]
Observed on Ada, using `MoveUntilTouchTopicController` and `JointTrajectoryController`. ROS's `velocity_controller/JointTrajectoryController` doesn't have this issue and it doesn't happen in simulation.

The robot moves along a trajectory. In the code, the related `future` object blocks execution while the robot is moving. However, `future.wait()` returns before the robot has actually finished moving. This leads to the program assuming the robot has finished moving and using the current pose for the next calculations, which can lead to all kinds of issue.

This behavior is especially visible on very long trajectories and there can be a difference of up to 4 seconds or larger between `future.wait()` returning and the robot actually stopping moving. If the trajectory is short, there is no noticable difference.

I tried  a couple of different PID values, ranging from p:3, d:0, i:0 to p:30, d:1, i:12 and the behavior seemed similar to me.

Proposed solution: The condition for a finished trajectory is found in [line 209 of JointTrajectoryControllerBase](https://github.com/personalrobotics/rewd_controllers/blob/master/src/JointTrajectoryControllerBase.cpp#L209). We can change that to something like `time >= trajectoryDuration && goalConstraintSatisfied`. For the goal constraint, we could use similar [parameters](http://wiki.ros.org/joint_trajectory_controller#Parameters) as ROS.

**Comment by brianhou** [comment]
I think this was resolved by #22. Feel free to reopen if this is not the case.
